name: Deploy Example

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: npm i
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
    - name: Build Example
      run: npm run build-example
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./example/build